// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    Board: typeof import('./src/components/Board.vue')['default']
    BoardCard: typeof import('./src/components/BoardCard.vue')['default']
    BoardsGrid: typeof import('./src/components/BoardsGrid.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
  }
}

export {}
